# Generated by Django 4.1.1 on 2022-09-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
